
export default {
  Base: '/api',
  Auth: {
    Base: '/auth',
    Login: '/login',
    Signup: '/signup',
    Logout: '/logout',
    ResetPassword: '/reset-password',
    VerifyOtp: '/verify-otp',
  },
  Users: {
    Base: '/users',
    Get: '/all',
    Add: '/add',
    Update: '/update',
    Delete: '/delete/:id',
    Profile: '/profile',
    UpdateProfile: '/profile/update',
  },
  Dashboard: {
    Base: '/dashboard',
    Overview: '/overview',
    Stats: '/stats',
  },
  Wallet: {
    Base: '/wallet',
    Balance: '/balance',
    TopUp: '/topup',
    Withdraw: '/withdraw',
    History: '/history',
  },
  Convert: {
    Base: '/convert',
    Exchange: '/exchange',
    Rates: '/rates',
    Calculate: '/calculate',
  },
  Transactions: {
    Base: '/transactions',
    All: '/all',
    UserHistory: '/history',
    Details: '/details/:id',
    UpdateStatus: '/status/:id',
  },
  Notifications: {
    Base: '/notifications',
    All: '/all',
    MarkRead: '/mark-read/:id',
    MarkAllRead: '/mark-all-read',
  },
  Settings: {
    Base: '/settings',
    Update: '/update',
    ChangePassword: '/change-password',
    Preferences: '/preferences',
  },
  Admin: {
    Base: '/admin',
    Login: '/login',
    Dashboard: '/dashboard',
    Transactions: {
      Base: '/transactions',
      All: '/all',
      Details: '/details/:id',
      Approve: '/approve/:id',
      Reject: '/reject/:id',
      UpdateStatus: '/status/:id',
    },
    Users: {
      Base: '/users',
      All: '/all',
      Details: '/details/:id',
      Block: '/block/:id',
      Unblock: '/unblock/:id',
      Delete: '/delete/:id',
    },
    Rates: {
      Base: '/rates',
      Get: '/get',
      Update: '/update',
      History: '/history',
    },
    Logs: {
      Base: '/logs',
      All: '/all',
      Notifications: '/notifications',
      Audit: '/audit',
    },
  },
  Webhooks: {
    Base: '/webhooks',
    Paystack: '/paystack',
    Momo: '/momo',
  },
} as const;
